# Generated by Django 5.2.4 on 2025-07-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandestock',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('transferee', 'Transférée'), ('traitee', 'Traitée')], default='en_attente', max_length=20),
        ),
    ]
