# Generated by Django 5.2.3 on 2025-06-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandestock',
            name='depot',
        ),
    ]
