# Generated by Django 5.2.3 on 2025-07-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_remove_demandestock_depot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('informatique', 'Informatique'), ('bureautique', 'Bureautique'), ('mobilier', 'Mobilier')], max_length=100),
        ),
    ]
