# Generated by Django 5.2.4 on 2025-07-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_alter_demandestock_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depot',
            name='libelle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
