# Generated by Django 5.2.3 on 2025-07-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_alter_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandestock',
            name='vue_par_utilisateur',
            field=models.BooleanField(default=False),
        ),
    ]
