# Generated by Django 5.2.3 on 2025-07-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_demandestock_vue_par_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandestock',
            name='vue_par_staff',
            field=models.BooleanField(default=False),
        ),
    ]
