# Generated by Django 5.2.3 on 2025-07-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_demandestock_vue_par_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='is_siege',
            field=models.BooleanField(default=False),
        ),
    ]
